version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    command: postgres -c 'shared_buffers=128MB' -c 'max_connections=50'
    environment:
      POSTGRES_USER: sensapi
      POSTGRES_PASSWORD: sensapi
      #PGDATA: /var/lib/postgresql/data/pgdata
    #volumes:
    #  - /data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432