name: Run tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Run tests inside Docker image
      run: docker build -f .github/workflows/test.Dockerfile -t solpor/solpor:latest .
